<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('items')->delete();
        
        \DB::table('items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Nike Air Zoom Pegasus 40',
                'slug' => 'nike-air-zoom-pegasus-40',
                'sku' => 'SKU1001',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '1_894e62e4-ac69-4696-aa89-4c8d03b80347_1024x1024.webp',
                'thumbnail' => '1_894e62e4-ac69-4696-aa89-4c8d03b80347_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 120.0,
                'previous_price' => 150.0,
                'stock' => 10,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "feature",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Adidas Ultraboost Light',
                'slug' => 'adidas-ultraboost-light',
                'sku' => 'SKU1002',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '1_57131a00-ccac-44f0-b935-80131c0fb14b_1024x1024.webp',
                'thumbnail' => '1_57131a00-ccac-44f0-b935-80131c0fb14b_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 130.0,
                'previous_price' => 160.0,
                'stock' => 15,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "feature",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Puma RS-X Reinvent',
                'slug' => 'puma-rs-x-reinvent',
                'sku' => 'SKU1003',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '1_4870127f-7197-4881-a5dc-5d4354ed941d_1024x1024.webp',
                'thumbnail' => '1_4870127f-7197-4881-a5dc-5d4354ed941d_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "feature",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'New Balance 550 Classic',
                'slug' => 'new-balance-550-classic',
                'sku' => 'SKU1004',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '1_73222429-92e9-4d56-a6e6-2bf1b71cb2df_1024x1024.webp',
                'thumbnail' => '1_73222429-92e9-4d56-a6e6-2bf1b71cb2df_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "feature",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Reebok Club C 85',
                'slug' => 'reebok-club-c-85',
                'sku' => 'SKU1005',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '1_b9172dd7-704a-40e7-8e7c-5ed0c7c9c09c_1024x1024.webp',
                'thumbnail' => '1_b9172dd7-704a-40e7-8e7c-5ed0c7c9c09c_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "new",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'ASICS Gel-Kayano 30',
                'slug' => 'asics-gel-kayano-30',
                'sku' => 'SKU1006',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '1_f6e8ed7c-1324-4063-8ebc-45695f5a2f81_1024x1024.webp',
                'thumbnail' => '1_f6e8ed7c-1324-4063-8ebc-45695f5a2f81_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "new",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Saucony Endorphin Speed 3',
                'slug' => 'saucony-endorphin-speed-3',
                'sku' => 'SKU1007',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '1_ef03206a-4d1d-4bd0-9016-29d2843e07e2_1024x1024.webp',
                'thumbnail' => '1_ef03206a-4d1d-4bd0-9016-29d2843e07e2_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "new",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Converse Chuck Taylor All Star',
                'slug' => 'converse-chuck-taylor-all-star',
                'sku' => 'SKU1008',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '5206170_1_1024x1024.webp',
                'thumbnail' => '5206170_1_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "new",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Vans Old Skool',
                'slug' => 'vans-old-skool',
                'sku' => 'SKU1009',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '5208167_1.webp',
                'thumbnail' => '5208167_1.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => NULL,
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Under Armour HOVR Phantom 3',
                'slug' => 'under-armour-hovr-phantom-3',
                'sku' => 'SKU1010',
                'code' => NULL,
                'tags' => NULL,
            'photo' => '5208169_1_1024x1024 (1).webp',
            'thumbnail' => '5208169_1_1024x1024 (1).webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "new",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => NULL,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Fila Disruptor II',
                'slug' => 'fila-disruptor-ii',
                'sku' => 'SKU1011',
                'code' => NULL,
                'tags' => NULL,
                'photo' => '5208169_1_1024x1024.webp',
                'thumbnail' => '5208169_1_1024x1024.webp',
                'video' => NULL,
                'file' => NULL,
                'file_type' => NULL,
                'link' => NULL,
                'sort_details' => '',
                'details' => NULL,
                'specification_name' => NULL,
                'specification_description' => NULL,
                'is_specification' => 0,
                'discount_price' => 140.0,
                'previous_price' => 170.0,
                'stock' => 8,
                'license_name' => NULL,
                'license_key' => NULL,
                'item_type' => 'normal',
                'affiliate_link' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'is_variant' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'status' => 1,
                'date' => NULL,
                'is_type' => "new",
                'created_at' => '2025-10-14 05:54:53',
                'updated_at' => '2025-10-14 05:54:53',
            ),
        ));
        
        
    }
}