<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItemsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $items = [
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Nike Air Zoom Pegasus 40',
                'slug' => 'nike-air-zoom-pegasus-40',
                'sku' => 'SKU1001',
                'photo' => '1_894e62e4-ac69-4696-aa89-4c8d03b80347_1024x1024.webp',
                'thumbnail' => '1_894e62e4-ac69-4696-aa89-4c8d03b80347_1024x1024.webp',
                'discount_price' => 120,
                'previous_price' => 150,
                'stock' => 10,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Adidas Ultraboost Light',
                'slug' => 'adidas-ultraboost-light',
                'sku' => 'SKU1002',
                'photo' => '1_57131a00-ccac-44f0-b935-80131c0fb14b_1024x1024.webp',
                'thumbnail' => '1_57131a00-ccac-44f0-b935-80131c0fb14b_1024x1024.webp',
                'discount_price' => 130,
                'previous_price' => 160,
                'stock' => 15,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Puma RS-X Reinvent',
                'slug' => 'puma-rs-x-reinvent',
                'sku' => 'SKU1003',
                'photo' => '1_4870127f-7197-4881-a5dc-5d4354ed941d_1024x1024.webp',
                'thumbnail' => '1_4870127f-7197-4881-a5dc-5d4354ed941d_1024x1024.webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'New Balance 550 Classic',
                'slug' => 'new-balance-550-classic',
                'sku' => 'SKU1004',
                'photo' => '1_73222429-92e9-4d56-a6e6-2bf1b71cb2df_1024x1024.webp',
                'thumbnail' => '1_73222429-92e9-4d56-a6e6-2bf1b71cb2df_1024x1024.webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Reebok Club C 85',
                'slug' => 'reebok-club-c-85',
                'sku' => 'SKU1005',
                'photo' => '1_b9172dd7-704a-40e7-8e7c-5ed0c7c9c09c_1024x1024.webp',
                'thumbnail' => '1_b9172dd7-704a-40e7-8e7c-5ed0c7c9c09c_1024x1024.webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'ASICS Gel-Kayano 30',
                'slug' => 'asics-gel-kayano-30',
                'sku' => 'SKU1006',
                'photo' => '1_f6e8ed7c-1324-4063-8ebc-45695f5a2f81_1024x1024.webp',
                'thumbnail' => '1_f6e8ed7c-1324-4063-8ebc-45695f5a2f81_1024x1024.webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Saucony Endorphin Speed 3',
                'slug' => 'saucony-endorphin-speed-3',
                'sku' => 'SKU1007',
                'photo' => '1_ef03206a-4d1d-4bd0-9016-29d2843e07e2_1024x1024.webp',
                'thumbnail' => '1_ef03206a-4d1d-4bd0-9016-29d2843e07e2_1024x1024.webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Converse Chuck Taylor All Star',
                'slug' => 'converse-chuck-taylor-all-star',
                'sku' => 'SKU1008',
                'photo' => '5206170_1_1024x1024.webp',
                'thumbnail' => '5206170_1_1024x1024.webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Vans Old Skool',
                'slug' => 'vans-old-skool',
                'sku' => 'SKU1009',
                'photo' => '5208167_1.webp',
                'thumbnail' => '5208167_1.webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Under Armour HOVR Phantom 3',
                'slug' => 'under-armour-hovr-phantom-3',
                'sku' => 'SKU1010',
                'photo' => '5208169_1_1024x1024 (1).webp',
                'thumbnail' => '5208169_1_1024x1024 (1).webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'childcategory_id' => null,
                'tax_id' => 3,
                'brand_id' => 1,
                'name' => 'Fila Disruptor II',
                'slug' => 'fila-disruptor-ii',
                'sku' => 'SKU1011',
                'photo' => '5208169_1_1024x1024.webp',
                'thumbnail' => '5208169_1_1024x1024.webp',
                'discount_price' => 140,
                'previous_price' => 170,
                'stock' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        
        Item::insert($items);
    }
}
