<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemVariantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('item_variants')->delete();
        
        \DB::table('item_variants')->insert(array (
            0 => 
            array (
                'id' => 17,
                'item_id' => 1,
                'variant_sku' => 'SKU1001-RED-M',
                'variant_id' => 1,
                'position' => 1,
                'item_code' => 'AJR1-RED-M',
                'additional_cost' => 5.0,
                'additional_price' => 10.0,
                'qty' => 5.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            1 => 
            array (
                'id' => 18,
                'item_id' => 1,
                'variant_sku' => 'SKU1001-BLUE-L',
                'variant_id' => 1,
                'position' => 2,
                'item_code' => 'AJR1-BLUE-L',
                'additional_cost' => 6.0,
                'additional_price' => 12.0,
                'qty' => 3.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            2 => 
            array (
                'id' => 19,
                'item_id' => 2,
                'variant_sku' => 'SKU1002-RED-M',
                'variant_id' => 1,
                'position' => 1,
                'item_code' => 'AJR2-RED-M',
                'additional_cost' => 5.0,
                'additional_price' => 10.0,
                'qty' => 7.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            3 => 
            array (
                'id' => 20,
                'item_id' => 3,
                'variant_sku' => 'SKU1003-BLACK-XL',
                'variant_id' => 1,
                'position' => 1,
                'item_code' => 'AJR3-BLACK-XL',
                'additional_cost' => 8.0,
                'additional_price' => 15.0,
                'qty' => 4.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            4 => 
            array (
                'id' => 21,
                'item_id' => 4,
                'variant_sku' => 'SKU1004-GREEN-S',
                'variant_id' => 16,
                'position' => 1,
                'item_code' => 'AJR4-GREEN-S',
                'additional_cost' => 7.0,
                'additional_price' => 14.0,
                'qty' => 10.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            5 => 
            array (
                'id' => 22,
                'item_id' => 5,
                'variant_sku' => 'SKU1005-YELLOW-M',
                'variant_id' => 17,
                'position' => 1,
                'item_code' => 'AJR5-YELLOW-M',
                'additional_cost' => 9.0,
                'additional_price' => 18.0,
                'qty' => 6.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            6 => 
            array (
                'id' => 23,
                'item_id' => 6,
                'variant_sku' => 'SKU1006-PURPLE-L',
                'variant_id' => 18,
                'position' => 1,
                'item_code' => 'AJR6-PURPLE-L',
                'additional_cost' => 5.0,
                'additional_price' => 11.0,
                'qty' => 8.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            7 => 
            array (
                'id' => 24,
                'item_id' => 7,
                'variant_sku' => 'SKU1007-PINK-XL',
                'variant_id' => 19,
                'position' => 1,
                'item_code' => 'AJR7-PINK-XL',
                'additional_cost' => 8.0,
                'additional_price' => 16.0,
                'qty' => 3.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            8 => 
            array (
                'id' => 25,
                'item_id' => 8,
                'variant_sku' => 'SKU1008-GRAY-XXL',
                'variant_id' => 20,
                'position' => 1,
                'item_code' => 'AJR8-GRAY-XXL',
                'additional_cost' => 10.0,
                'additional_price' => 20.0,
                'qty' => 5.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            9 => 
            array (
                'id' => 26,
                'item_id' => 9,
                'variant_sku' => 'SKU1009-ORANGE-S',
                'variant_id' => 21,
                'position' => 1,
                'item_code' => 'AJR9-ORANGE-S',
                'additional_cost' => 6.0,
                'additional_price' => 13.0,
                'qty' => 7.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            10 => 
            array (
                'id' => 27,
                'item_id' => 10,
                'variant_sku' => 'SKU1010-WHITE-M',
                'variant_id' => 22,
                'position' => 1,
                'item_code' => 'AJR10-WHITE-M',
                'additional_cost' => 7.0,
                'additional_price' => 14.0,
                'qty' => 9.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            11 => 
            array (
                'id' => 28,
                'item_id' => 11,
                'variant_sku' => 'SKU1011-BROWN-L',
                'variant_id' => 23,
                'position' => 1,
                'item_code' => 'AJR11-BROWN-L',
                'additional_cost' => 9.0,
                'additional_price' => 17.0,
                'qty' => 4.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            12 => 
            array (
                'id' => 29,
                'item_id' => 12,
                'variant_sku' => 'SKU1012-CYAN-XL',
                'variant_id' => 24,
                'position' => 1,
                'item_code' => 'AJR12-CYAN-XL',
                'additional_cost' => 8.0,
                'additional_price' => 16.0,
                'qty' => 6.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            13 => 
            array (
                'id' => 30,
                'item_id' => 13,
                'variant_sku' => 'SKU1013-MAGENTA-XXL',
                'variant_id' => 25,
                'position' => 1,
                'item_code' => 'AJR13-MAGENTA-XXL',
                'additional_cost' => 11.0,
                'additional_price' => 22.0,
                'qty' => 2.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            14 => 
            array (
                'id' => 31,
                'item_id' => 14,
                'variant_sku' => 'SKU1014-LIME-S',
                'variant_id' => 26,
                'position' => 1,
                'item_code' => 'AJR14-LIME-S',
                'additional_cost' => 6.0,
                'additional_price' => 12.0,
                'qty' => 8.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-10-14 11:54:53',
            ),
            15 => 
            array (
                'id' => 32,
                'item_id' => 15,
                'variant_sku' => 'SKU1015-TEAL-M',
                'variant_id' => 27,
                'position' => 1,
                'item_code' => 'Black/6/r4er53',
                'additional_cost' => 7.0,
                'additional_price' => 14.0,
                'qty' => 0.0,
                'created_at' => '2025-10-14 11:54:53',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            16 => 
            array (
                'id' => 33,
                'item_id' => 12,
                'variant_sku' => 'xxx',
                'variant_id' => 31,
                'position' => 1,
                'item_code' => 'Blue/44/xxx',
                'additional_cost' => 120.0,
                'additional_price' => 110.0,
                'qty' => 0.0,
                'created_at' => '2025-11-27 16:03:46',
                'updated_at' => '2025-11-27 16:03:46',
            ),
            17 => 
            array (
                'id' => 34,
                'item_id' => 12,
                'variant_sku' => '12',
                'variant_id' => 32,
                'position' => 2,
                'item_code' => 'Blue/43/xxx',
                'additional_cost' => 120.0,
                'additional_price' => 110.0,
                'qty' => 0.0,
                'created_at' => '2025-11-27 16:03:46',
                'updated_at' => '2025-11-27 16:03:46',
            ),
            18 => 
            array (
                'id' => 35,
                'item_id' => 12,
                'variant_sku' => '23',
                'variant_id' => 33,
                'position' => 3,
                'item_code' => 'Blue/42/xxx',
                'additional_cost' => 120.0,
                'additional_price' => 110.0,
                'qty' => 0.0,
                'created_at' => '2025-11-27 16:03:46',
                'updated_at' => '2025-11-27 16:03:46',
            ),
            19 => 
            array (
                'id' => 36,
                'item_id' => 12,
                'variant_sku' => '34',
                'variant_id' => 34,
                'position' => 4,
                'item_code' => 'Black/44/xxx',
                'additional_cost' => 120.0,
                'additional_price' => 110.0,
                'qty' => 0.0,
                'created_at' => '2025-11-27 16:03:46',
                'updated_at' => '2025-11-27 16:03:46',
            ),
            20 => 
            array (
                'id' => 37,
                'item_id' => 12,
                'variant_sku' => '45',
                'variant_id' => 35,
                'position' => 5,
                'item_code' => 'Black/43/xxx',
                'additional_cost' => 120.0,
                'additional_price' => 110.0,
                'qty' => 0.0,
                'created_at' => '2025-11-27 16:03:46',
                'updated_at' => '2025-11-27 16:03:46',
            ),
            21 => 
            array (
                'id' => 38,
                'item_id' => 12,
                'variant_sku' => '56',
                'variant_id' => 36,
                'position' => 6,
                'item_code' => 'Black/42/xxx',
                'additional_cost' => 120.0,
                'additional_price' => 110.0,
                'qty' => 0.0,
                'created_at' => '2025-11-27 16:03:46',
                'updated_at' => '2025-11-27 16:03:46',
            ),
            22 => 
            array (
                'id' => 39,
                'item_id' => 13,
                'variant_sku' => '12',
                'variant_id' => 31,
                'position' => 1,
                'item_code' => 'Blue/44/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            23 => 
            array (
                'id' => 40,
                'item_id' => 13,
                'variant_sku' => '123',
                'variant_id' => 32,
                'position' => 2,
                'item_code' => 'Blue/43/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            24 => 
            array (
                'id' => 41,
                'item_id' => 13,
                'variant_sku' => '11',
                'variant_id' => 33,
                'position' => 3,
                'item_code' => 'Blue/42/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            25 => 
            array (
                'id' => 42,
                'item_id' => 13,
                'variant_sku' => '33',
                'variant_id' => 37,
                'position' => 4,
                'item_code' => 'Blue/41/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            26 => 
            array (
                'id' => 43,
                'item_id' => 13,
                'variant_sku' => '22',
                'variant_id' => 38,
                'position' => 5,
                'item_code' => 'Blue/40/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            27 => 
            array (
                'id' => 44,
                'item_id' => 13,
                'variant_sku' => '44',
                'variant_id' => 39,
                'position' => 6,
                'item_code' => 'Blue/39/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            28 => 
            array (
                'id' => 45,
                'item_id' => 13,
                'variant_sku' => '55',
                'variant_id' => 34,
                'position' => 7,
                'item_code' => 'Black/44/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            29 => 
            array (
                'id' => 46,
                'item_id' => 13,
                'variant_sku' => '66',
                'variant_id' => 35,
                'position' => 8,
                'item_code' => 'Black/43/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            30 => 
            array (
                'id' => 47,
                'item_id' => 13,
                'variant_sku' => '77',
                'variant_id' => 36,
                'position' => 9,
                'item_code' => 'Black/42/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            31 => 
            array (
                'id' => 48,
                'item_id' => 13,
                'variant_sku' => '88',
                'variant_id' => 40,
                'position' => 10,
                'item_code' => 'Black/41/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            32 => 
            array (
                'id' => 49,
                'item_id' => 13,
                'variant_sku' => '99',
                'variant_id' => 41,
                'position' => 11,
                'item_code' => 'Black/40/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            33 => 
            array (
                'id' => 50,
                'item_id' => 13,
                'variant_sku' => '100',
                'variant_id' => 42,
                'position' => 12,
                'item_code' => 'Black/39/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            34 => 
            array (
                'id' => 51,
                'item_id' => 13,
                'variant_sku' => '20',
                'variant_id' => 43,
                'position' => 13,
                'item_code' => 'Red/44/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            35 => 
            array (
                'id' => 52,
                'item_id' => 13,
                'variant_sku' => '30',
                'variant_id' => 44,
                'position' => 14,
                'item_code' => 'Red/43/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            36 => 
            array (
                'id' => 53,
                'item_id' => 13,
                'variant_sku' => '40',
                'variant_id' => 45,
                'position' => 15,
                'item_code' => 'Red/42/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            37 => 
            array (
                'id' => 54,
                'item_id' => 13,
                'variant_sku' => '50',
                'variant_id' => 46,
                'position' => 16,
                'item_code' => 'Red/41/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            38 => 
            array (
                'id' => 55,
                'item_id' => 13,
                'variant_sku' => '00',
                'variant_id' => 47,
                'position' => 17,
                'item_code' => 'Red/40/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            39 => 
            array (
                'id' => 56,
                'item_id' => 13,
                'variant_sku' => '60',
                'variant_id' => 48,
                'position' => 18,
                'item_code' => 'Red/39/1212',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 12:40:03',
                'updated_at' => '2025-11-29 12:40:03',
            ),
            40 => 
            array (
                'id' => 57,
                'item_id' => 14,
                'variant_sku' => '11',
                'variant_id' => 31,
                'position' => 1,
                'item_code' => 'Blue/44/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            41 => 
            array (
                'id' => 58,
                'item_id' => 14,
                'variant_sku' => '12',
                'variant_id' => 32,
                'position' => 2,
                'item_code' => 'Blue/43/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            42 => 
            array (
                'id' => 59,
                'item_id' => 14,
                'variant_sku' => '123',
                'variant_id' => 33,
                'position' => 3,
                'item_code' => 'Blue/42/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            43 => 
            array (
                'id' => 60,
                'item_id' => 14,
                'variant_sku' => '1234',
                'variant_id' => 37,
                'position' => 4,
                'item_code' => 'Blue/41/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            44 => 
            array (
                'id' => 61,
                'item_id' => 14,
                'variant_sku' => 'dfd',
                'variant_id' => 38,
                'position' => 5,
                'item_code' => 'Blue/40/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            45 => 
            array (
                'id' => 62,
                'item_id' => 14,
                'variant_sku' => 'fdr',
                'variant_id' => 39,
                'position' => 6,
                'item_code' => 'Blue/39/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            46 => 
            array (
                'id' => 63,
                'item_id' => 14,
                'variant_sku' => 'cfdf',
                'variant_id' => 34,
                'position' => 7,
                'item_code' => 'Black/44/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            47 => 
            array (
                'id' => 64,
                'item_id' => 14,
                'variant_sku' => 'cd',
                'variant_id' => 35,
                'position' => 8,
                'item_code' => 'Black/43/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            48 => 
            array (
                'id' => 65,
                'item_id' => 14,
                'variant_sku' => 'cdr',
                'variant_id' => 36,
                'position' => 9,
                'item_code' => 'Black/42/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            49 => 
            array (
                'id' => 66,
                'item_id' => 14,
                'variant_sku' => 'gr',
                'variant_id' => 40,
                'position' => 10,
                'item_code' => 'Black/41/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            50 => 
            array (
                'id' => 67,
                'item_id' => 14,
                'variant_sku' => 'ngh',
                'variant_id' => 41,
                'position' => 11,
                'item_code' => 'Black/40/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            51 => 
            array (
                'id' => 68,
                'item_id' => 14,
                'variant_sku' => 'cvdf',
                'variant_id' => 42,
                'position' => 12,
                'item_code' => 'Black/39/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            52 => 
            array (
                'id' => 69,
                'item_id' => 14,
                'variant_sku' => 'fdrf',
                'variant_id' => 43,
                'position' => 13,
                'item_code' => 'Red/44/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            53 => 
            array (
                'id' => 70,
                'item_id' => 14,
                'variant_sku' => 'b fg',
                'variant_id' => 44,
                'position' => 14,
                'item_code' => 'Red/43/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            54 => 
            array (
                'id' => 71,
                'item_id' => 14,
                'variant_sku' => 'bfrtg',
                'variant_id' => 45,
                'position' => 15,
                'item_code' => 'Red/42/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            55 => 
            array (
                'id' => 72,
                'item_id' => 14,
                'variant_sku' => 'vbfgt',
                'variant_id' => 46,
                'position' => 16,
                'item_code' => 'Red/41/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            56 => 
            array (
                'id' => 73,
                'item_id' => 14,
                'variant_sku' => 'vbrt',
                'variant_id' => 47,
                'position' => 17,
                'item_code' => 'Red/40/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            57 => 
            array (
                'id' => 74,
                'item_id' => 14,
                'variant_sku' => 'dftfer',
                'variant_id' => 48,
                'position' => 18,
                'item_code' => 'Red/39/ferrfd',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-29 14:57:18',
                'updated_at' => '2025-11-29 14:57:18',
            ),
            58 => 
            array (
                'id' => 75,
                'item_id' => 15,
                'variant_sku' => '11',
                'variant_id' => 31,
                'position' => 2,
                'item_code' => 'Blue/44/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            59 => 
            array (
                'id' => 76,
                'item_id' => 15,
                'variant_sku' => '22',
                'variant_id' => 32,
                'position' => 3,
                'item_code' => 'Blue/43/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            60 => 
            array (
                'id' => 77,
                'item_id' => 15,
                'variant_sku' => '33',
                'variant_id' => 33,
                'position' => 4,
                'item_code' => 'Blue/42/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            61 => 
            array (
                'id' => 78,
                'item_id' => 15,
                'variant_sku' => '44',
                'variant_id' => 37,
                'position' => 5,
                'item_code' => 'Blue/41/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            62 => 
            array (
                'id' => 79,
                'item_id' => 15,
                'variant_sku' => '55',
                'variant_id' => 38,
                'position' => 6,
                'item_code' => 'Blue/40/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            63 => 
            array (
                'id' => 80,
                'item_id' => 15,
                'variant_sku' => '66',
                'variant_id' => 39,
                'position' => 7,
                'item_code' => 'Blue/39/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            64 => 
            array (
                'id' => 81,
                'item_id' => 15,
                'variant_sku' => '77',
                'variant_id' => 34,
                'position' => 8,
                'item_code' => 'Black/44/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            65 => 
            array (
                'id' => 82,
                'item_id' => 15,
                'variant_sku' => '88',
                'variant_id' => 35,
                'position' => 9,
                'item_code' => 'Black/43/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            66 => 
            array (
                'id' => 83,
                'item_id' => 15,
                'variant_sku' => '99',
                'variant_id' => 36,
                'position' => 10,
                'item_code' => 'Black/42/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            67 => 
            array (
                'id' => 84,
                'item_id' => 15,
                'variant_sku' => '00',
                'variant_id' => 40,
                'position' => 11,
                'item_code' => 'Black/41/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            68 => 
            array (
                'id' => 85,
                'item_id' => 15,
                'variant_sku' => 'qq',
                'variant_id' => 41,
                'position' => 12,
                'item_code' => 'Black/40/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            69 => 
            array (
                'id' => 86,
                'item_id' => 15,
                'variant_sku' => 'ww',
                'variant_id' => 42,
                'position' => 13,
                'item_code' => 'Black/39/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            70 => 
            array (
                'id' => 87,
                'item_id' => 15,
                'variant_sku' => 'ee',
                'variant_id' => 43,
                'position' => 14,
                'item_code' => 'Red/44/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            71 => 
            array (
                'id' => 88,
                'item_id' => 15,
                'variant_sku' => 'rr',
                'variant_id' => 44,
                'position' => 15,
                'item_code' => 'Red/43/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            72 => 
            array (
                'id' => 89,
                'item_id' => 15,
                'variant_sku' => 'tt',
                'variant_id' => 45,
                'position' => 16,
                'item_code' => 'Red/42/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            73 => 
            array (
                'id' => 90,
                'item_id' => 15,
                'variant_sku' => 'yy',
                'variant_id' => 46,
                'position' => 17,
                'item_code' => 'Red/41/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            74 => 
            array (
                'id' => 91,
                'item_id' => 15,
                'variant_sku' => 'tuu',
                'variant_id' => 47,
                'position' => 18,
                'item_code' => 'Red/40/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
            75 => 
            array (
                'id' => 92,
                'item_id' => 15,
                'variant_sku' => 'oo',
                'variant_id' => 48,
                'position' => 19,
                'item_code' => 'Red/39/r4er53',
                'additional_cost' => 0.0,
                'additional_price' => 0.0,
                'qty' => 0.0,
                'created_at' => '2025-11-30 10:58:07',
                'updated_at' => '2025-12-20 14:18:16',
            ),
        ));
        
        
    }
}