<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 122,
                'user_id' => 0,
                'cart' => '{"535-Red,M":{"options_id":[269,1094],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"2021 Summer Women Clothing Ropa Sexy Lady Cut Out Halter Mini Dresses","slug":"-----Summer-Women-Clothing-Ropa-Sexy-Lady-Cut-Out-Halter-Mini-Dresses","qty":"1","price":144.830000000000012505552149377763271331787109375,"main_price":134.830000000000012505552149377763271331787109375,"photo":"1634135320H408d7d7e37b4437297de600584c1af1fL.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":1,"title":"Free Delevery","price":0,"minimum_price":1000,"is_condition":1,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Cash On Delivery',
                'txnid' => NULL,
                'tax' => 1.3483,
                'charge_id' => NULL,
                'transaction_number' => 'zNF5gDbPnM',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"showrav","ship_last_name":"Hasan","ship_email":"teacher@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"Munshinogor,Delduar,Tangail,Dhaka,Bangladesh","ship_address2":null,"ship_zip":"1234","ship_city":"Tangail...","ship_country":"Bangladesh"}',
                'billing_info' => '{"_token":"QOD5MKmJWvK28KB8O9k913pbovZvrzIHs89Ac2KK","bill_first_name":"showrav","bill_last_name":"Hasan","bill_email":"teacher@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"Munshinogor,Delduar,Tangail,Dhaka,Bangladesh","bill_address2":null,"bill_zip":"1234","bill_city":"Tangail...","bill_country":"Bangladesh","same_ship_address":"on"}',
                'payment_status' => 'Unpaid',
                'created_at' => '2022-01-16 15:37:45',
                'updated_at' => '2022-01-16 15:37:45',
                'state_price' => 14.483,
                'state' => '{"id":6,"name":"India","price":10,"status":1,"type":"fixed"}',
            ),
            1 => 
            array (
                'id' => 123,
                'user_id' => 1,
                'cart' => '{"587-Red,M":{"options_id":[429,1126],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"New French Elegant White Bubble Sleeve Party Dress Casual A-Line Dresses, Long Sleeve Dresses","slug":"0AENew-French-Elegant-White-Bubble-Sleeve-Party-Dress-Casual-ALine-Dresses-Long-Sleeve-DressesnC","qty":"1","price":344.82999999999998408384271897375583648681640625,"main_price":334.82999999999998408384271897375583648681640625,"photo":"1634134144H03667d1e3ae44be08f32b72d840db095J.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":1,"title":"Free Delevery","price":0,"minimum_price":1000,"is_condition":1,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Stripe',
                'txnid' => 'txn_3KIb9QH3jdWvr8gE1Ph1bOxa',
                'tax' => 3.3483,
                'charge_id' => 'ch_3KIb9QH3jdWvr8gE1d2Ivr4f',
                'transaction_number' => 'ZN6ve2FsBf',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":"United States"}',
                'billing_info' => '{"_token":"QOD5MKmJWvK28KB8O9k913pbovZvrzIHs89Ac2KK","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"472 Clark Street,  Bay Shore, New York","bill_address2":null,"bill_zip":"3444","bill_city":"New York","bill_country":"United States","same_ship_address":"on"}',
                'payment_status' => 'Paid',
                'created_at' => '2022-01-16 16:00:15',
                'updated_at' => '2022-01-16 16:00:15',
                'state_price' => 34.483,
                'state' => '{"id":6,"name":"India","price":10,"status":1,"type":"percentage"}',
            ),
            2 => 
            array (
                'id' => 124,
                'user_id' => 1,
                'cart' => '{"534-Red,M":{"options_id":[265,1093],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"Top Sale High Quality Newest Designs Custom Women Clothing Wholesale from China Dresses","slug":"Top-Sale-High-Quality-Newest-Designs-Custom-Women-Clothing-Wholesale-from-China-Dresses","qty":"1","price":69.5499999999999971578290569595992565155029296875,"main_price":59.5499999999999971578290569595992565155029296875,"photo":"1634135337H948b3bef197c492d999473dffa5303f9P.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":1,"title":"Free Delevery","price":0,"minimum_price":1000,"is_condition":1,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Cash On Delivery',
                'txnid' => NULL,
                'tax' => 0.5955,
                'charge_id' => NULL,
                'transaction_number' => 'GPt4RZ0RCq',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":"United States"}',
                'billing_info' => '{"_token":"QOD5MKmJWvK28KB8O9k913pbovZvrzIHs89Ac2KK","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"472 Clark Street,  Bay Shore, New York","bill_address2":null,"bill_zip":"3444","bill_city":"New York","bill_country":"United States","same_ship_address":"on"}',
                'payment_status' => 'Unpaid',
                'created_at' => '2022-01-16 16:03:35',
                'updated_at' => '2022-01-16 16:03:35',
                'state_price' => 6.955,
                'state' => '{"id":6,"name":"India","price":10,"status":1,"type":"percentage"}',
            ),
            3 => 
            array (
                'id' => 125,
                'user_id' => 1,
                'cart' => '{"534-Red,M":{"options_id":[265,1093],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"Top Sale High Quality Newest Designs Custom Women Clothing Wholesale from China Dresses","slug":"Top-Sale-High-Quality-Newest-Designs-Custom-Women-Clothing-Wholesale-from-China-Dresses","qty":"1","price":69.5499999999999971578290569595992565155029296875,"main_price":59.5499999999999971578290569595992565155029296875,"photo":"1634135337H948b3bef197c492d999473dffa5303f9P.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":2,"title":"Delivery","price":20,"minimum_price":0,"is_condition":0,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Cash On Delivery',
                'txnid' => NULL,
                'tax' => 0.5955,
                'charge_id' => NULL,
                'transaction_number' => '0HGakDhxlW',
                'order_status' => 'In Progress',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":"United States"}',
                'billing_info' => '{"_token":"QOD5MKmJWvK28KB8O9k913pbovZvrzIHs89Ac2KK","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"472 Clark Street,  Bay Shore, New York","bill_address2":null,"bill_zip":"3444","bill_city":"New York","bill_country":"United States","same_ship_address":"on"}',
                'payment_status' => 'Unpaid',
                'created_at' => '2022-01-16 16:08:36',
                'updated_at' => '2022-02-28 14:24:36',
                'state_price' => 6.955,
                'state' => '{"id":6,"name":"India","price":10,"status":1,"type":"percentage"}',
            ),
            4 => 
            array (
                'id' => 126,
                'user_id' => 1,
                'cart' => '{"587-Pink,XXL":{"options_id":[432,1264],"attribute":{"names":["Color","Size"],"option_name":["Pink","XXL"],"option_price":[8,7]},"attribute_price":15,"name":"New French Elegant White Bubble Sleeve Party Dress Casual A-Line Dresses, Long Sleeve Dresses","slug":"0AENew-French-Elegant-White-Bubble-Sleeve-Party-Dress-Casual-ALine-Dresses-Long-Sleeve-DressesnC","qty":"2","price":344.82999999999998408384271897375583648681640625,"main_price":334.82999999999998408384271897375583648681640625,"photo":"1634134144H03667d1e3ae44be08f32b72d840db095J.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":2,"title":"Delivery","price":20,"minimum_price":0,"is_condition":0,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Stripe',
                'txnid' => 'txn_3KIcZsH3jdWvr8gE1xCmNaNe',
                'tax' => 3.3483,
                'charge_id' => 'ch_3KIcZsH3jdWvr8gE1g4sD0jO',
                'transaction_number' => 'Ffr4zOVXnf',
                'order_status' => 'Delivered',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":"United States"}',
                'billing_info' => '{"_token":"72BuSB7wcI55oScnzMJaMuCK0ZBFOdNoLGTqPuI0","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"472 Clark Street,  Bay Shore, New York","bill_address2":null,"bill_zip":"3444","bill_city":"New York","bill_country":"United States","same_ship_address":"on"}',
                'payment_status' => 'Paid',
                'created_at' => '2022-01-16 17:31:41',
                'updated_at' => '2022-01-17 09:59:27',
                'state_price' => 68.466,
                'state' => '{"id":6,"name":"India","price":10,"status":1,"type":"percentage"}',
            ),
            5 => 
            array (
                'id' => 127,
                'user_id' => 1,
                'cart' => '{"587-Pink,XXL":{"options_id":[432,1264],"attribute":{"names":["Color","Size"],"option_name":["Pink","XXL"],"option_price":[8,7]},"attribute_price":15,"name":"New French Elegant White Bubble Sleeve Party Dress Casual A-Line Dresses, Long Sleeve Dresses","slug":"0AENew-French-Elegant-White-Bubble-Sleeve-Party-Dress-Casual-ALine-Dresses-Long-Sleeve-DressesnC","qty":"1","price":344.82999999999998408384271897375583648681640625,"main_price":334.82999999999998408384271897375583648681640625,"photo":"1634134144H03667d1e3ae44be08f32b72d840db095J.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":2,"title":"Delivery","price":20,"minimum_price":0,"is_condition":0,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Paypal',
                'txnid' => '0JS90047YT3185603',
                'tax' => 1.0,
                'charge_id' => NULL,
                'transaction_number' => 'rTgJph3cv8',
                'order_status' => 'Delivered',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":"United States"}',
                'billing_info' => '{"_token":"72BuSB7wcI55oScnzMJaMuCK0ZBFOdNoLGTqPuI0","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"472 Clark Street,  Bay Shore, New York","bill_address2":null,"bill_zip":"3444","bill_city":"New York","bill_country":"United States","same_ship_address":"on"}',
                'payment_status' => 'Paid',
                'created_at' => '2022-01-16 17:33:57',
                'updated_at' => '2022-01-17 09:59:21',
                'state_price' => 34.983,
                'state' => '{"id":6,"name":"India","price":10,"status":1,"type":"percentage"}',
            ),
            6 => 
            array (
                'id' => 128,
                'user_id' => 1,
                'cart' => '{"539-Pink,XXL":{"options_id":[288,1236],"attribute":{"names":["Color","Size"],"option_name":["Pink","XXL"],"option_price":[8,7]},"attribute_price":15,"name":"Clothing Women 2021 New Fashion Printed Knitwear Round Neck Casual Couple Clothing Christmas","slug":"Clothing-Women------New-Fashion-Printed-Knitwear-Round-Neck-Casual-Couple-Clothing-Christmas","qty":"2","price":66.18000000000000682121026329696178436279296875,"main_price":56.17999999999999971578290569595992565155029296875,"photo":"1634134958H8b2502797ffe4c93984c99bdd5061ab3W.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":2,"title":"Delivery","price":20,"minimum_price":0,"is_condition":0,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Stripe',
                'txnid' => 'txn_3KIcesH3jdWvr8gE17fmrDps',
                'tax' => 0.5618,
                'charge_id' => 'ch_3KIcesH3jdWvr8gE1bWbzyns',
                'transaction_number' => 'JrV7oupswB',
                'order_status' => 'Delivered',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":"United States"}',
                'billing_info' => '{"_token":"72BuSB7wcI55oScnzMJaMuCK0ZBFOdNoLGTqPuI0","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"472 Clark Street,  Bay Shore, New York","bill_address2":null,"bill_zip":"3444","bill_city":"New York","bill_country":"United States","same_ship_address":"on"}',
                'payment_status' => 'Paid',
                'created_at' => '2022-01-16 17:36:51',
                'updated_at' => '2022-01-17 09:59:15',
                'state_price' => 12.736,
                'state' => '{"id":6,"name":"India","price":10,"status":1,"type":"percentage"}',
            ),
            7 => 
            array (
                'id' => 129,
                'user_id' => 1,
                'cart' => '{"586-Red,M":{"options_id":[425,1125],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"BREYLEE facial mask hyaluronic acid facial firming mask beauty","slug":"Td5BREYLEE-facial-mask-hyaluronic-acid-facial-firming-mask-beautyca","qty":"1","price":1362.80999999999994543031789362430572509765625,"main_price":1352.80999999999994543031789362430572509765625,"photo":"1634134188HTB1ymRhXfjsK1Rjy1Xaq6zispXad.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":1,"title":"Free Delevery","price":0,"minimum_price":1000,"is_condition":1,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Stripe',
                'txnid' => 'txn_3KIcihH3jdWvr8gE1jYOlJfQ',
                'tax' => 13.5281,
                'charge_id' => 'ch_3KIcihH3jdWvr8gE164YxcvT',
                'transaction_number' => 'HhgjzEg09z',
                'order_status' => 'Delivered',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":"United States"}',
                'billing_info' => '{"_token":"72BuSB7wcI55oScnzMJaMuCK0ZBFOdNoLGTqPuI0","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"472 Clark Street,  Bay Shore, New York","bill_address2":null,"bill_zip":"3444","bill_city":"New York","bill_country":"United States","same_ship_address":"on"}',
                'payment_status' => 'Paid',
                'created_at' => '2022-01-16 17:40:48',
                'updated_at' => '2022-01-17 09:59:09',
                'state_price' => 136.281,
                'state' => '{"id":6,"name":"India","price":10,"status":1,"type":"percentage"}',
            ),
            8 => 
            array (
                'id' => 130,
                'user_id' => 1,
                'cart' => '{"535-Red,M":{"options_id":[269,1094],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"2021 Summer Women Clothing Ropa Sexy Lady Cut Out Halter Mini Dresses","slug":"-----Summer-Women-Clothing-Ropa-Sexy-Lady-Cut-Out-Halter-Mini-Dresses","qty":"1","price":144.830000000000012505552149377763271331787109375,"main_price":134.830000000000012505552149377763271331787109375,"photo":"1634135320H408d7d7e37b4437297de600584c1af1fL.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":2,"title":"Delivery","price":20,"minimum_price":0,"is_condition":0,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Cash On Delivery',
                'txnid' => NULL,
                'tax' => 1.3483,
                'charge_id' => NULL,
                'transaction_number' => 'j0W5sAeolz',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"showrav","ship_last_name":"Hasan","ship_email":"showrabhasan715@gmail.com","ship_phone":"0172833200","ship_company":null,"ship_address1":"Dhaka,Bangladesh","ship_address2":null,"ship_zip":"1234","ship_city":"Tangail...","ship_country":"Bangladesh"}',
                'billing_info' => '{"_token":"qm68PlIpjNaoP7Tkcz9JT55huv8mzjCgs8YnHJsW","bill_first_name":"showrav","bill_last_name":"Hasan","bill_email":"showrabhasan715@gmail.com","bill_phone":"0172833200","bill_company":null,"bill_address1":"Dhaka,Bangladesh","bill_address2":null,"bill_zip":"1234","bill_city":"Tangail...","bill_country":"Bangladesh","same_ship_address":"on"}',
                'payment_status' => 'Unpaid',
                'created_at' => '2022-03-01 16:10:39',
                'updated_at' => '2022-03-01 16:10:39',
                'state_price' => 5.7932,
                'state' => '{"id":7,"name":"California","price":4,"status":1,"type":"percentage"}',
            ),
            9 => 
            array (
                'id' => 131,
                'user_id' => 1,
                'cart' => '{"587-Red,M":{"options_id":[429,1126],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"New French Elegant White Bubble Sleeve Party Dress Casual A-Line Dresses, Long Sleeve Dresses","slug":"0AENew-French-Elegant-White-Bubble-Sleeve-Party-Dress-Casual-ALine-Dresses-Long-Sleeve-DressesnC","qty":"1","price":344.83,"main_price":334.83,"photo":"1634134144H03667d1e3ae44be08f32b72d840db095J.jpg","item_type":"normal","item_l_n":null,"item_l_k":null},"586-Red,M":{"options_id":[425,1125],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"BREYLEE facial mask hyaluronic acid facial firming mask beauty","slug":"Td5BREYLEE-facial-mask-hyaluronic-acid-facial-firming-mask-beautyca","qty":"1","price":1362.81,"main_price":1352.81,"photo":"1634134188HTB1ymRhXfjsK1Rjy1Xaq6zispXad.jpg","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":1,"title":"Free Delevery","price":0,"minimum_price":1000,"is_condition":1,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Cash On Delivery',
                'txnid' => NULL,
                'tax' => 16.8764,
                'charge_id' => NULL,
                'transaction_number' => 'TyExwhsbeS',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":"United States"}',
                'billing_info' => '{"_token":"wMuLFwlTenaXlbg4ZZk2UrBZxBHJqtgBs8USQUmC","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_company":null,"bill_address1":"472 Clark Street,  Bay Shore, New York","bill_address2":null,"bill_zip":"3444","bill_city":"New York","bill_country":"United States","same_ship_address":"on"}',
                'payment_status' => 'Unpaid',
                'created_at' => '2022-03-02 08:15:49',
                'updated_at' => '2022-03-02 08:15:49',
                'state_price' => 0.0,
                'state' => NULL,
            ),
            10 => 
            array (
                'id' => 132,
                'user_id' => 1,
                'cart' => '{"577-":{"options_id":[],"attribute":{"names":[],"option_name":[],"option_price":[]},"attribute_price":0,"name":"Best Online Wholesale Website Design and development company | Ecommerce shopping webdesign","slug":"fgcBest-Online-Wholesale-Website-Design-and-development-company--Ecommerce-shopping-webdesign8q","qty":"1","price":35,"main_price":35,"photo":"1634134411Ucc4d26e9889041dc899c3522859ed3f88.jpg","item_type":"license","item_l_n":"5","item_l_k":"5"}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":2,"title":"Delivery","price":20,"minimum_price":0,"is_condition":0,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Stripe',
                'txnid' => 'txn_3KYnNsH3jdWvr8gE0GZ6b8YQ',
                'tax' => 0.35,
                'charge_id' => 'ch_3KYnNsH3jdWvr8gE0WD94EcP',
                'transaction_number' => 'w10xGWiN80',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009"}',
                'billing_info' => '{"_token":"wMuLFwlTenaXlbg4ZZk2UrBZxBHJqtgBs8USQUmC","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","same_ship_address":"on"}',
                'payment_status' => 'Paid',
                'created_at' => '2022-03-02 08:18:08',
                'updated_at' => '2022-03-02 08:18:08',
                'state_price' => 0.0,
                'state' => NULL,
            ),
            11 => 
            array (
                'id' => 133,
                'user_id' => 1,
                'cart' => '{"586-Red,M":{"options_id":[425,1125],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"BREYLEE facial mask hyaluronic acid facial firming mask beauty","slug":"Td5BREYLEE-facial-mask-hyaluronic-acid-facial-firming-mask-beautyca","qty":"1","price":1362.81,"main_price":1352.81,"photo":"1634134188HTB1ymRhXfjsK1Rjy1Xaq6zispXad.jpg","type":"normal","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":1,"title":"Free Delevery","price":0,"minimum_price":1000,"is_condition":1,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Cash On Delivery',
                'txnid' => NULL,
                'tax' => 13.5281,
                'charge_id' => NULL,
                'transaction_number' => 'ORD-20250413-133',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":null}',
                'billing_info' => '{"_token":"suef2R0IZFBTrPBLn9bsRywqs3nb2ZmKoKUPOgc8","payment_method":"Cash On Delivery","state_id":"10","shipping_id":"1","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_address1":"472 Clark Street,  Bay Shore, New York","bill_zip":"3444","bill_city":"New York"}',
                'payment_status' => 'Unpaid',
                'created_at' => '2025-04-13 21:53:01',
                'updated_at' => '2025-04-13 21:53:01',
                'state_price' => 81.7686,
                'state' => '{"id":10,"name":"Virginia","price":6,"status":1,"type":"percentage"}',
            ),
            12 => 
            array (
                'id' => 134,
                'user_id' => 0,
                'cart' => '{"594-500ml":{"options_id":[1265],"attribute":{"names":["Weight"],"option_name":["500ml"],"option_price":[100]},"attribute_price":100,"name":"Honey","slug":"Honey","qty":"1","price":100,"main_price":0,"photo":"OM_1745772286v8jlTKP9.jpg","type":"normal","item_type":"normal","item_l_n":null,"item_l_k":null},"587-Red,M":{"options_id":[429,1126],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"New French Elegant White Bubble Sleeve Party Dress Casual A-Line Dresses, Long Sleeve Dresses","slug":"0AENew-French-Elegant-White-Bubble-Sleeve-Party-Dress-Casual-ALine-Dresses-Long-Sleeve-DressesnC","qty":"1","price":344.83,"main_price":334.83,"photo":"1634134144H03667d1e3ae44be08f32b72d840db095J.jpg","type":"normal","item_type":"normal","item_l_n":null,"item_l_k":null},"544-Red,M":{"options_id":[305,1103],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"Wholesale Price 1.3 Mega HD DV SLR Camera, 2.4 inch LCD Full HD 720P Recording, EIS, Supply Drops","slug":"Wholesale-Price-----Mega-HD-DV-SLR-Camera------inch-LCD-Full-HD----P-Recording--EIS--Supply-Drops","qty":"1","price":156.07,"main_price":146.07,"photo":"1634134872HTB1BqH4aIfrK1RkSmLyq6xGApXaJ.jpg","type":"normal","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":2,"title":"Delivery","price":20,"minimum_price":0,"is_condition":0,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Cash On Delivery',
                'txnid' => NULL,
                'tax' => 4.809,
                'charge_id' => NULL,
                'transaction_number' => 'ORD-20250427-134',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"Mamunur","ship_last_name":"Rashid","ship_email":"mamunurrashid6424@gmail.com","ship_phone":"01795846424","ship_company":null,"ship_address1":"Ring Road, Mohammadpur, House 18\\/5, Floor - 2nd Dhaka, 1207, Dhaka, Bangladesh","ship_address2":null,"ship_zip":"1207","ship_city":"Dhaka Metro","ship_country":null}',
                'billing_info' => '{"_token":"rjPNZ6X0RCled5ZzefD4gqm3bNQjOKRshhFVjET5","payment_method":"Cash On Delivery","state_id":"8","shipping_id":"2","single_page_checkout":"1","bill_first_name":"Mamunur","bill_last_name":"Rashid","bill_email":"mamunurrashid6424@gmail.com","bill_phone":"01795846424","bill_address1":"Ring Road, Mohammadpur, House 18\\/5, Floor - 2nd Dhaka, 1207, Dhaka, Bangladesh","bill_zip":"1207","bill_city":"Dhaka Metro"}',
                'payment_status' => 'Unpaid',
                'created_at' => '2025-04-27 20:05:39',
                'updated_at' => '2025-04-27 20:05:39',
                'state_price' => 30.045,
                'state' => '{"id":8,"name":"New Mexico","price":5,"status":1,"type":"percentage"}',
            ),
            13 => 
            array (
                'id' => 135,
                'user_id' => 1,
                'cart' => '{"594-500ml":{"options_id":[1265],"attribute":{"names":["Weight"],"option_name":["500ml"],"option_price":[100]},"attribute_price":100,"name":"Honey","slug":"Honey","qty":"1","price":100,"main_price":0,"photo":"OM_1745772286v8jlTKP9.jpg","type":"normal","item_type":"normal","item_l_n":null,"item_l_k":null},"587-Red,M":{"options_id":[429,1126],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"New French Elegant White Bubble Sleeve Party Dress Casual A-Line Dresses, Long Sleeve Dresses","slug":"0AENew-French-Elegant-White-Bubble-Sleeve-Party-Dress-Casual-ALine-Dresses-Long-Sleeve-DressesnC","qty":"1","price":344.83,"main_price":334.83,"photo":"1634134144H03667d1e3ae44be08f32b72d840db095J.jpg","type":"normal","item_type":"normal","item_l_n":null,"item_l_k":null},"544-Red,M":{"options_id":[305,1103],"attribute":{"names":["Color","Size"],"option_name":["Red","M"],"option_price":[5,5]},"attribute_price":10,"name":"Wholesale Price 1.3 Mega HD DV SLR Camera, 2.4 inch LCD Full HD 720P Recording, EIS, Supply Drops","slug":"Wholesale-Price-----Mega-HD-DV-SLR-Camera------inch-LCD-Full-HD----P-Recording--EIS--Supply-Drops","qty":"1","price":156.07,"main_price":146.07,"photo":"1634134872HTB1BqH4aIfrK1RkSmLyq6xGApXaJ.jpg","type":"normal","item_type":"normal","item_l_n":null,"item_l_k":null}}',
                'currency_sign' => '$',
                'currency_value' => '1',
                'discount' => '[]',
                'shipping' => '{"id":2,"title":"Delivery","price":20,"minimum_price":0,"is_condition":0,"status":1,"created_at":null,"updated_at":null}',
                'payment_method' => 'Cash On Delivery',
                'txnid' => NULL,
                'tax' => 4.809,
                'charge_id' => NULL,
                'transaction_number' => 'ORD-20250427-135',
                'order_status' => 'Pending',
                'shipping_info' => '{"ship_first_name":"Alex","ship_last_name":"Smith","ship_email":"user@gmail.com","ship_phone":"01728332009","ship_company":null,"ship_address1":"472 Clark Street,  Bay Shore, New York","ship_address2":null,"ship_zip":"3444","ship_city":"New York","ship_country":null}',
                'billing_info' => '{"_token":"rjPNZ6X0RCled5ZzefD4gqm3bNQjOKRshhFVjET5","payment_method":"Cash On Delivery","state_id":"8","shipping_id":"2","single_page_checkout":"1","bill_first_name":"Alex","bill_last_name":"Smith","bill_email":"user@gmail.com","bill_phone":"01728332009","bill_address1":"472 Clark Street,  Bay Shore, New York","bill_zip":"3444","bill_city":"New York"}',
                'payment_status' => 'Unpaid',
                'created_at' => '2025-04-27 20:06:24',
                'updated_at' => '2025-04-27 20:06:24',
                'state_price' => 30.045,
                'state' => '{"id":8,"name":"New Mexico","price":5,"status":1,"type":"percentage"}',
            ),
        ));
        
        
    }
}